admin_home_page:
    pattern: /admin
    defaults: {_controller: RAAFPAGEUserBundle:Admin:home }
seller_home_page:
    pattern: /seller
    defaults: {_controller: RAAFPAGEUserBundle:Admin:seller }

add_account:
    path:     /register
    defaults: { _controller: RAAFPAGEUserBundle:Admin:addAccount }


login:
    path:     /login
    defaults: { _controller: RAAFPAGEUserBundle:Security:login }

login_check:
    pattern:   /admin/login_check

logout:
    pattern:    /admin/logout
