raafpage_site:
    resource: "@RAAFPAGESiteBundle/Resources/config/routing.yml"
    prefix:   /

raafpage_ad:
    resource: "@RAAFPAGEAdBundle/Controller/"
    type:     annotation
    prefix:   /

RAAFPAGE_user:
    resource: "@RAAFPAGEUserBundle/Controller/"
    type:     annotation
    prefix:   /

post:
    resource: "@RAAFPAGEFileManagerBundle/Controller/TopicController.php"
    type:     annotation

login_check:
    pattern:   /admin/login_check

logout:
    pattern:    /admin/logout
