site_unsecured_page:
    pattern: /
    defaults: {_controller: HRPROJECTUserBundle:Default:index }

site_home_page:
    pattern: /secured
    defaults: {_controller: HRPROJECTUserBundle:Default:home }

admin_home_page:
    pattern: /admin
    defaults: {_controller: HRPROJECTUserBundle:Admin:home }
seller_home_page:
    pattern: /seller
    defaults: {_controller: HRPROJECTUserBundle:Admin:seller }

add_account:
    path:     /register
    defaults: { _controller: HRPROJECTUserBundle:Admin:addAccount }


login:
    path:     /login
    defaults: { _controller: HRPROJECTUserBundle:Security:login }

login_check:
    pattern:   /admin/login_check

logout:
    pattern:    /admin/logout
