RAAFPAGE_file_manager_upload_document:
    path:     /upload
    defaults: { _controller: RAAFPAGEFileManagerBundle:Default:upload }
RAAFPAGE_file_manager_document_list:
    path:     /list
    defaults: { _controller: RAAFPAGEFileManagerBundle:Default:list }
